name: hijri
description: >
  Convert between Hijri and  Gregorian calendar days.
version: 0.2.5
author: Ahmed Aljuaid <aljo3aid@gmail.com>
email: aljo3aid@gmail.com
homepage: http://www.ummulqura.org.sa/

environment:
  sdk: '>=2.0.0 <3.0.0'


dev_dependencies:
  test: "^0.12.38+1"
